# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import streamflow_pb2 as streamflow__pb2


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Produce = channel.unary_unary(
                '/streamflow.v1.MessageService/Produce',
                request_serializer=streamflow__pb2.ProduceRequest.SerializeToString,
                response_deserializer=streamflow__pb2.ProduceResponse.FromString,
                )
        self.Consume = channel.unary_stream(
                '/streamflow.v1.MessageService/Consume',
                request_serializer=streamflow__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=streamflow__pb2.ConsumeResponse.FromString,
                )
        self.ConsumeBatch = channel.unary_unary(
                '/streamflow.v1.MessageService/ConsumeBatch',
                request_serializer=streamflow__pb2.ConsumeRequest.SerializeToString,
                response_deserializer=streamflow__pb2.ConsumeResponse.FromString,
                )
        self.CommitOffset = channel.unary_unary(
                '/streamflow.v1.MessageService/CommitOffset',
                request_serializer=streamflow__pb2.CommitOffsetRequest.SerializeToString,
                response_deserializer=streamflow__pb2.CommitOffsetResponse.FromString,
                )
        self.GetOffset = channel.unary_unary(
                '/streamflow.v1.MessageService/GetOffset',
                request_serializer=streamflow__pb2.GetOffsetRequest.SerializeToString,
                response_deserializer=streamflow__pb2.GetOffsetResponse.FromString,
                )
        self.Health = channel.unary_unary(
                '/streamflow.v1.MessageService/Health',
                request_serializer=streamflow__pb2.HealthRequest.SerializeToString,
                response_deserializer=streamflow__pb2.HealthResponse.FromString,
                )


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Produce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsumeBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOffset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Produce': grpc.unary_unary_rpc_method_handler(
                    servicer.Produce,
                    request_deserializer=streamflow__pb2.ProduceRequest.FromString,
                    response_serializer=streamflow__pb2.ProduceResponse.SerializeToString,
            ),
            'Consume': grpc.unary_stream_rpc_method_handler(
                    servicer.Consume,
                    request_deserializer=streamflow__pb2.ConsumeRequest.FromString,
                    response_serializer=streamflow__pb2.ConsumeResponse.SerializeToString,
            ),
            'ConsumeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsumeBatch,
                    request_deserializer=streamflow__pb2.ConsumeRequest.FromString,
                    response_serializer=streamflow__pb2.ConsumeResponse.SerializeToString,
            ),
            'CommitOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitOffset,
                    request_deserializer=streamflow__pb2.CommitOffsetRequest.FromString,
                    response_serializer=streamflow__pb2.CommitOffsetResponse.SerializeToString,
            ),
            'GetOffset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOffset,
                    request_deserializer=streamflow__pb2.GetOffsetRequest.FromString,
                    response_serializer=streamflow__pb2.GetOffsetResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=streamflow__pb2.HealthRequest.FromString,
                    response_serializer=streamflow__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamflow.v1.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Produce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.MessageService/Produce',
            streamflow__pb2.ProduceRequest.SerializeToString,
            streamflow__pb2.ProduceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/streamflow.v1.MessageService/Consume',
            streamflow__pb2.ConsumeRequest.SerializeToString,
            streamflow__pb2.ConsumeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConsumeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.MessageService/ConsumeBatch',
            streamflow__pb2.ConsumeRequest.SerializeToString,
            streamflow__pb2.ConsumeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.MessageService/CommitOffset',
            streamflow__pb2.CommitOffsetRequest.SerializeToString,
            streamflow__pb2.CommitOffsetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOffset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.MessageService/GetOffset',
            streamflow__pb2.GetOffsetRequest.SerializeToString,
            streamflow__pb2.GetOffsetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.MessageService/Health',
            streamflow__pb2.HealthRequest.SerializeToString,
            streamflow__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class PartitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPartitions = channel.unary_unary(
                '/streamflow.v1.PartitionService/ListPartitions',
                request_serializer=streamflow__pb2.ListPartitionsRequest.SerializeToString,
                response_deserializer=streamflow__pb2.ListPartitionsResponse.FromString,
                )
        self.RebalancePartitions = channel.unary_unary(
                '/streamflow.v1.PartitionService/RebalancePartitions',
                request_serializer=streamflow__pb2.RebalanceRequest.SerializeToString,
                response_deserializer=streamflow__pb2.RebalanceResponse.FromString,
                )
        self.GetPartitionMetrics = channel.unary_unary(
                '/streamflow.v1.PartitionService/GetPartitionMetrics',
                request_serializer=streamflow__pb2.PartitionMetricsRequest.SerializeToString,
                response_deserializer=streamflow__pb2.PartitionMetricsResponse.FromString,
                )
        self.ScalePartitions = channel.unary_unary(
                '/streamflow.v1.PartitionService/ScalePartitions',
                request_serializer=streamflow__pb2.ScalePartitionsRequest.SerializeToString,
                response_deserializer=streamflow__pb2.ScalePartitionsResponse.FromString,
                )


class PartitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListPartitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebalancePartitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartitionMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScalePartitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPartitions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPartitions,
                    request_deserializer=streamflow__pb2.ListPartitionsRequest.FromString,
                    response_serializer=streamflow__pb2.ListPartitionsResponse.SerializeToString,
            ),
            'RebalancePartitions': grpc.unary_unary_rpc_method_handler(
                    servicer.RebalancePartitions,
                    request_deserializer=streamflow__pb2.RebalanceRequest.FromString,
                    response_serializer=streamflow__pb2.RebalanceResponse.SerializeToString,
            ),
            'GetPartitionMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartitionMetrics,
                    request_deserializer=streamflow__pb2.PartitionMetricsRequest.FromString,
                    response_serializer=streamflow__pb2.PartitionMetricsResponse.SerializeToString,
            ),
            'ScalePartitions': grpc.unary_unary_rpc_method_handler(
                    servicer.ScalePartitions,
                    request_deserializer=streamflow__pb2.ScalePartitionsRequest.FromString,
                    response_serializer=streamflow__pb2.ScalePartitionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamflow.v1.PartitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PartitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPartitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.PartitionService/ListPartitions',
            streamflow__pb2.ListPartitionsRequest.SerializeToString,
            streamflow__pb2.ListPartitionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RebalancePartitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.PartitionService/RebalancePartitions',
            streamflow__pb2.RebalanceRequest.SerializeToString,
            streamflow__pb2.RebalanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPartitionMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.PartitionService/GetPartitionMetrics',
            streamflow__pb2.PartitionMetricsRequest.SerializeToString,
            streamflow__pb2.PartitionMetricsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ScalePartitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.PartitionService/ScalePartitions',
            streamflow__pb2.ScalePartitionsRequest.SerializeToString,
            streamflow__pb2.ScalePartitionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ConsumerGroupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGroup = channel.unary_unary(
                '/streamflow.v1.ConsumerGroupService/JoinGroup',
                request_serializer=streamflow__pb2.JoinGroupRequest.SerializeToString,
                response_deserializer=streamflow__pb2.JoinGroupResponse.FromString,
                )
        self.LeaveGroup = channel.unary_unary(
                '/streamflow.v1.ConsumerGroupService/LeaveGroup',
                request_serializer=streamflow__pb2.LeaveGroupRequest.SerializeToString,
                response_deserializer=streamflow__pb2.LeaveGroupResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/streamflow.v1.ConsumerGroupService/Heartbeat',
                request_serializer=streamflow__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=streamflow__pb2.HeartbeatResponse.FromString,
                )
        self.GetGroupInfo = channel.unary_unary(
                '/streamflow.v1.ConsumerGroupService/GetGroupInfo',
                request_serializer=streamflow__pb2.GroupInfoRequest.SerializeToString,
                response_deserializer=streamflow__pb2.GroupInfoResponse.FromString,
                )


class ConsumerGroupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGroup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsumerGroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGroup,
                    request_deserializer=streamflow__pb2.JoinGroupRequest.FromString,
                    response_serializer=streamflow__pb2.JoinGroupResponse.SerializeToString,
            ),
            'LeaveGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGroup,
                    request_deserializer=streamflow__pb2.LeaveGroupRequest.FromString,
                    response_serializer=streamflow__pb2.LeaveGroupResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=streamflow__pb2.HeartbeatRequest.FromString,
                    response_serializer=streamflow__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetGroupInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupInfo,
                    request_deserializer=streamflow__pb2.GroupInfoRequest.FromString,
                    response_serializer=streamflow__pb2.GroupInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streamflow.v1.ConsumerGroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConsumerGroupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.ConsumerGroupService/JoinGroup',
            streamflow__pb2.JoinGroupRequest.SerializeToString,
            streamflow__pb2.JoinGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.ConsumerGroupService/LeaveGroup',
            streamflow__pb2.LeaveGroupRequest.SerializeToString,
            streamflow__pb2.LeaveGroupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.ConsumerGroupService/Heartbeat',
            streamflow__pb2.HeartbeatRequest.SerializeToString,
            streamflow__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGroupInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streamflow.v1.ConsumerGroupService/GetGroupInfo',
            streamflow__pb2.GroupInfoRequest.SerializeToString,
            streamflow__pb2.GroupInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
