// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/proto/streamflow.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_streamflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Message) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ProduceResult       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{2}
}

func (x *ProduceResponse) GetResults() []*ProduceResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProduceResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResult) Reset() {
	*x = ProduceResult{}
	mi := &file_api_proto_streamflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResult) ProtoMessage() {}

func (x *ProduceResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResult.ProtoReflect.Descriptor instead.
func (*ProduceResult) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{3}
}

func (x *ProduceResult) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ProduceResult) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ProduceResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,5,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{4}
}

func (x *ConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *ConsumeRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *ConsumeRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ConsumeRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumeResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConsumeResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ConsumeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Partition Management Messages
type ListPartitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsRequest) Reset() {
	*x = ListPartitionsRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsRequest) ProtoMessage() {}

func (x *ListPartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsRequest.ProtoReflect.Descriptor instead.
func (*ListPartitionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{8}
}

func (x *ListPartitionsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ListPartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*PartitionInfo       `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartitionsResponse) Reset() {
	*x = ListPartitionsResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartitionsResponse) ProtoMessage() {}

func (x *ListPartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartitionsResponse.ProtoReflect.Descriptor instead.
func (*ListPartitionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{9}
}

func (x *ListPartitionsResponse) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type PartitionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	MessageCount  int64                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	BytesStored   int64                  `protobuf:"varint,3,opt,name=bytes_stored,json=bytesStored,proto3" json:"bytes_stored,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	Leader        string                 `protobuf:"bytes,5,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
	mi := &file_api_proto_streamflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionInfo.ProtoReflect.Descriptor instead.
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{10}
}

func (x *PartitionInfo) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionInfo) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *PartitionInfo) GetBytesStored() int64 {
	if x != nil {
		return x.BytesStored
	}
	return 0
}

func (x *PartitionInfo) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *PartitionInfo) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

type RebalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"` // "round_robin", "range", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebalanceRequest) Reset() {
	*x = RebalanceRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceRequest) ProtoMessage() {}

func (x *RebalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceRequest.ProtoReflect.Descriptor instead.
func (*RebalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{11}
}

func (x *RebalanceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RebalanceRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type RebalanceResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PartitionAssignments map[int32]string       `protobuf:"bytes,3,rep,name=partition_assignments,json=partitionAssignments,proto3" json:"partition_assignments,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // partition -> consumer
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RebalanceResponse) Reset() {
	*x = RebalanceResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebalanceResponse) ProtoMessage() {}

func (x *RebalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebalanceResponse.ProtoReflect.Descriptor instead.
func (*RebalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{12}
}

func (x *RebalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RebalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RebalanceResponse) GetPartitionAssignments() map[int32]string {
	if x != nil {
		return x.PartitionAssignments
	}
	return nil
}

type PartitionMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"` // -1 for all partitions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetricsRequest) Reset() {
	*x = PartitionMetricsRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetricsRequest) ProtoMessage() {}

func (x *PartitionMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetricsRequest.ProtoReflect.Descriptor instead.
func (*PartitionMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{13}
}

func (x *PartitionMetricsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PartitionMetricsRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type PartitionMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*PartitionMetrics    `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetricsResponse) Reset() {
	*x = PartitionMetricsResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetricsResponse) ProtoMessage() {}

func (x *PartitionMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetricsResponse.ProtoReflect.Descriptor instead.
func (*PartitionMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{14}
}

func (x *PartitionMetricsResponse) GetMetrics() []*PartitionMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type PartitionMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   int32                  `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	MessageCount  int64                  `protobuf:"varint,2,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	BytesStored   int64                  `protobuf:"varint,3,opt,name=bytes_stored,json=bytesStored,proto3" json:"bytes_stored,omitempty"`
	ProduceRate   float64                `protobuf:"fixed64,4,opt,name=produce_rate,json=produceRate,proto3" json:"produce_rate,omitempty"`
	ConsumeRate   float64                `protobuf:"fixed64,5,opt,name=consume_rate,json=consumeRate,proto3" json:"consume_rate,omitempty"`
	LastActivity  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionMetrics) Reset() {
	*x = PartitionMetrics{}
	mi := &file_api_proto_streamflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMetrics) ProtoMessage() {}

func (x *PartitionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMetrics.ProtoReflect.Descriptor instead.
func (*PartitionMetrics) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{15}
}

func (x *PartitionMetrics) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionMetrics) GetMessageCount() int64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *PartitionMetrics) GetBytesStored() int64 {
	if x != nil {
		return x.BytesStored
	}
	return 0
}

func (x *PartitionMetrics) GetProduceRate() float64 {
	if x != nil {
		return x.ProduceRate
	}
	return 0
}

func (x *PartitionMetrics) GetConsumeRate() float64 {
	if x != nil {
		return x.ConsumeRate
	}
	return 0
}

func (x *PartitionMetrics) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

type ScalePartitionsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Topic             string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NewPartitionCount int32                  `protobuf:"varint,2,opt,name=new_partition_count,json=newPartitionCount,proto3" json:"new_partition_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScalePartitionsRequest) Reset() {
	*x = ScalePartitionsRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalePartitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalePartitionsRequest) ProtoMessage() {}

func (x *ScalePartitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalePartitionsRequest.ProtoReflect.Descriptor instead.
func (*ScalePartitionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{16}
}

func (x *ScalePartitionsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ScalePartitionsRequest) GetNewPartitionCount() int32 {
	if x != nil {
		return x.NewPartitionCount
	}
	return 0
}

type ScalePartitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	OldCount      int32                  `protobuf:"varint,3,opt,name=old_count,json=oldCount,proto3" json:"old_count,omitempty"`
	NewCount      int32                  `protobuf:"varint,4,opt,name=new_count,json=newCount,proto3" json:"new_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScalePartitionsResponse) Reset() {
	*x = ScalePartitionsResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScalePartitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScalePartitionsResponse) ProtoMessage() {}

func (x *ScalePartitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScalePartitionsResponse.ProtoReflect.Descriptor instead.
func (*ScalePartitionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{17}
}

func (x *ScalePartitionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScalePartitionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ScalePartitionsResponse) GetOldCount() int32 {
	if x != nil {
		return x.OldCount
	}
	return 0
}

func (x *ScalePartitionsResponse) GetNewCount() int32 {
	if x != nil {
		return x.NewCount
	}
	return 0
}

// Consumer Group Messages
type JoinGroupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId       string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	GroupId          string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Topics           []string               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"`
	SessionTimeoutMs int32                  `protobuf:"varint,4,opt,name=session_timeout_ms,json=sessionTimeoutMs,proto3" json:"session_timeout_ms,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{18}
}

func (x *JoinGroupRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *JoinGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *JoinGroupRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *JoinGroupRequest) GetSessionTimeoutMs() int32 {
	if x != nil {
		return x.SessionTimeoutMs
	}
	return 0
}

func (x *JoinGroupRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type JoinGroupResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedPartitions []int32                `protobuf:"varint,3,rep,packed,name=assigned_partitions,json=assignedPartitions,proto3" json:"assigned_partitions,omitempty"`
	GroupState         string                 `protobuf:"bytes,4,opt,name=group_state,json=groupState,proto3" json:"group_state,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{19}
}

func (x *JoinGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinGroupResponse) GetAssignedPartitions() []int32 {
	if x != nil {
		return x.AssignedPartitions
	}
	return nil
}

func (x *JoinGroupResponse) GetGroupState() string {
	if x != nil {
		return x.GroupState
	}
	return ""
}

type LeaveGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{20}
}

func (x *LeaveGroupRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type LeaveGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupResponse) Reset() {
	*x = LeaveGroupResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupResponse) ProtoMessage() {}

func (x *LeaveGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupResponse.ProtoReflect.Descriptor instead.
func (*LeaveGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{21}
}

func (x *LeaveGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ShouldRebalance bool                   `protobuf:"varint,3,opt,name=should_rebalance,json=shouldRebalance,proto3" json:"should_rebalance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{23}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HeartbeatResponse) GetShouldRebalance() bool {
	if x != nil {
		return x.ShouldRebalance
	}
	return false
}

type GroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoRequest) Reset() {
	*x = GroupInfoRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoRequest) ProtoMessage() {}

func (x *GroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{24}
}

func (x *GroupInfoRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Members       []*ConsumerMember      `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Topics        []string               `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastRebalance *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_rebalance,json=lastRebalance,proto3" json:"last_rebalance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoResponse) Reset() {
	*x = GroupInfoResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoResponse) ProtoMessage() {}

func (x *GroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoResponse.ProtoReflect.Descriptor instead.
func (*GroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{25}
}

func (x *GroupInfoResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInfoResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GroupInfoResponse) GetMembers() []*ConsumerMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GroupInfoResponse) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *GroupInfoResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GroupInfoResponse) GetLastRebalance() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRebalance
	}
	return nil
}

type ConsumerMember struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId         string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	AssignedPartitions []int32                `protobuf:"varint,2,rep,packed,name=assigned_partitions,json=assignedPartitions,proto3" json:"assigned_partitions,omitempty"`
	State              string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	LastHeartbeat      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConsumerMember) Reset() {
	*x = ConsumerMember{}
	mi := &file_api_proto_streamflow_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumerMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerMember) ProtoMessage() {}

func (x *ConsumerMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerMember.ProtoReflect.Descriptor instead.
func (*ConsumerMember) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{26}
}

func (x *ConsumerMember) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumerMember) GetAssignedPartitions() []int32 {
	if x != nil {
		return x.AssignedPartitions
	}
	return nil
}

func (x *ConsumerMember) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ConsumerMember) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *ConsumerMember) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Offset management messages
type CommitOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetRequest) Reset() {
	*x = CommitOffsetRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetRequest) ProtoMessage() {}

func (x *CommitOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetRequest.ProtoReflect.Descriptor instead.
func (*CommitOffsetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{27}
}

func (x *CommitOffsetRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *CommitOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CommitOffsetRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *CommitOffsetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CommitOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetResponse) Reset() {
	*x = CommitOffsetResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetResponse) ProtoMessage() {}

func (x *CommitOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetResponse.ProtoReflect.Descriptor instead.
func (*CommitOffsetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{28}
}

func (x *CommitOffsetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitOffsetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Partition     int32                  `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetRequest) Reset() {
	*x = GetOffsetRequest{}
	mi := &file_api_proto_streamflow_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetRequest) ProtoMessage() {}

func (x *GetOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetRequest.ProtoReflect.Descriptor instead.
func (*GetOffsetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{29}
}

func (x *GetOffsetRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *GetOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetOffsetRequest) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type GetOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetResponse) Reset() {
	*x = GetOffsetResponse{}
	mi := &file_api_proto_streamflow_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetResponse) ProtoMessage() {}

func (x *GetOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_streamflow_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetResponse.ProtoReflect.Descriptor instead.
func (*GetOffsetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_streamflow_proto_rawDescGZIP(), []int{30}
}

func (x *GetOffsetResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetOffsetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_streamflow_proto protoreflect.FileDescriptor

const file_api_proto_streamflow_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/streamflow.proto\x12\rstreamflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x01\n" +
	"\aMessage\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\"Z\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x122\n" +
	"\bmessages\x18\x02 \x03(\v2\x16.streamflow.v1.MessageR\bmessages\"I\n" +
	"\x0fProduceResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.streamflow.v1.ProduceResultR\aresults\"[\n" +
	"\rProduceResult\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa6\x01\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\x12!\n" +
	"\fmax_messages\x18\x05 \x01(\x05R\vmaxMessages\"v\n" +
	"\x0fConsumeResponse\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.streamflow.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0f\n" +
	"\rHealthRequest\"\xc4\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12D\n" +
	"\ametrics\x18\x03 \x03(\v2*.streamflow.v1.HealthResponse.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x15ListPartitionsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"V\n" +
	"\x16ListPartitionsResponse\x12<\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x1c.streamflow.v1.PartitionInfoR\n" +
	"partitions\"\xd3\x01\n" +
	"\rPartitionInfo\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x03R\fmessageCount\x12!\n" +
	"\fbytes_stored\x18\x03 \x01(\x03R\vbytesStored\x12?\n" +
	"\rlast_activity\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12\x16\n" +
	"\x06leader\x18\x05 \x01(\tR\x06leader\"D\n" +
	"\x10RebalanceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\"\x81\x02\n" +
	"\x11RebalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12o\n" +
	"\x15partition_assignments\x18\x03 \x03(\v2:.streamflow.v1.RebalanceResponse.PartitionAssignmentsEntryR\x14partitionAssignments\x1aG\n" +
	"\x19PartitionAssignmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x17PartitionMetricsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\"U\n" +
	"\x18PartitionMetricsResponse\x129\n" +
	"\ametrics\x18\x01 \x03(\v2\x1f.streamflow.v1.PartitionMetricsR\ametrics\"\x84\x02\n" +
	"\x10PartitionMetrics\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\x05R\vpartitionId\x12#\n" +
	"\rmessage_count\x18\x02 \x01(\x03R\fmessageCount\x12!\n" +
	"\fbytes_stored\x18\x03 \x01(\x03R\vbytesStored\x12!\n" +
	"\fproduce_rate\x18\x04 \x01(\x01R\vproduceRate\x12!\n" +
	"\fconsume_rate\x18\x05 \x01(\x01R\vconsumeRate\x12?\n" +
	"\rlast_activity\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\"^\n" +
	"\x16ScalePartitionsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12.\n" +
	"\x13new_partition_count\x18\x02 \x01(\x05R\x11newPartitionCount\"\x87\x01\n" +
	"\x17ScalePartitionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\told_count\x18\x03 \x01(\x05R\boldCount\x12\x1b\n" +
	"\tnew_count\x18\x04 \x01(\x05R\bnewCount\"\x9c\x02\n" +
	"\x10JoinGroupRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\x12,\n" +
	"\x12session_timeout_ms\x18\x04 \x01(\x05R\x10sessionTimeoutMs\x12I\n" +
	"\bmetadata\x18\x05 \x03(\v2-.streamflow.v1.JoinGroupRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\x11JoinGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x13assigned_partitions\x18\x03 \x03(\x05R\x12assignedPartitions\x12\x1f\n" +
	"\vgroup_state\x18\x04 \x01(\tR\n" +
	"groupState\"4\n" +
	"\x11LeaveGroupRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\"H\n" +
	"\x12LeaveGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\"r\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10should_rebalance\x18\x03 \x01(\bR\x0fshouldRebalance\"-\n" +
	"\x10GroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\x93\x02\n" +
	"\x11GroupInfoResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x127\n" +
	"\amembers\x18\x03 \x03(\v2\x1d.streamflow.v1.ConsumerMemberR\amembers\x12\x16\n" +
	"\x06topics\x18\x04 \x03(\tR\x06topics\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\x0elast_rebalance\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastRebalance\"\xc1\x02\n" +
	"\x0eConsumerMember\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12/\n" +
	"\x13assigned_partitions\x18\x02 \x03(\x05R\x12assignedPartitions\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.streamflow.v1.ConsumerMember.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x13CommitOffsetRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"F\n" +
	"\x14CommitOffsetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"m\n" +
	"\x10GetOffsetRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tpartition\x18\x03 \x01(\x05R\tpartition\"A\n" +
	"\x11GetOffsetResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xe5\x03\n" +
	"\x0eMessageService\x12H\n" +
	"\aProduce\x12\x1d.streamflow.v1.ProduceRequest\x1a\x1e.streamflow.v1.ProduceResponse\x12J\n" +
	"\aConsume\x12\x1d.streamflow.v1.ConsumeRequest\x1a\x1e.streamflow.v1.ConsumeResponse0\x01\x12M\n" +
	"\fConsumeBatch\x12\x1d.streamflow.v1.ConsumeRequest\x1a\x1e.streamflow.v1.ConsumeResponse\x12W\n" +
	"\fCommitOffset\x12\".streamflow.v1.CommitOffsetRequest\x1a#.streamflow.v1.CommitOffsetResponse\x12N\n" +
	"\tGetOffset\x12\x1f.streamflow.v1.GetOffsetRequest\x1a .streamflow.v1.GetOffsetResponse\x12E\n" +
	"\x06Health\x12\x1c.streamflow.v1.HealthRequest\x1a\x1d.streamflow.v1.HealthResponse2\x95\x03\n" +
	"\x10PartitionService\x12]\n" +
	"\x0eListPartitions\x12$.streamflow.v1.ListPartitionsRequest\x1a%.streamflow.v1.ListPartitionsResponse\x12X\n" +
	"\x13RebalancePartitions\x12\x1f.streamflow.v1.RebalanceRequest\x1a .streamflow.v1.RebalanceResponse\x12f\n" +
	"\x13GetPartitionMetrics\x12&.streamflow.v1.PartitionMetricsRequest\x1a'.streamflow.v1.PartitionMetricsResponse\x12`\n" +
	"\x0fScalePartitions\x12%.streamflow.v1.ScalePartitionsRequest\x1a&.streamflow.v1.ScalePartitionsResponse2\xdc\x02\n" +
	"\x14ConsumerGroupService\x12N\n" +
	"\tJoinGroup\x12\x1f.streamflow.v1.JoinGroupRequest\x1a .streamflow.v1.JoinGroupResponse\x12Q\n" +
	"\n" +
	"LeaveGroup\x12 .streamflow.v1.LeaveGroupRequest\x1a!.streamflow.v1.LeaveGroupResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.streamflow.v1.HeartbeatRequest\x1a .streamflow.v1.HeartbeatResponse\x12Q\n" +
	"\fGetGroupInfo\x12\x1f.streamflow.v1.GroupInfoRequest\x1a .streamflow.v1.GroupInfoResponseB/Z-github.com/Anujtr/streamflow-engine/api/protob\x06proto3"

var (
	file_api_proto_streamflow_proto_rawDescOnce sync.Once
	file_api_proto_streamflow_proto_rawDescData []byte
)

func file_api_proto_streamflow_proto_rawDescGZIP() []byte {
	file_api_proto_streamflow_proto_rawDescOnce.Do(func() {
		file_api_proto_streamflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_streamflow_proto_rawDesc), len(file_api_proto_streamflow_proto_rawDesc)))
	})
	return file_api_proto_streamflow_proto_rawDescData
}

var file_api_proto_streamflow_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_api_proto_streamflow_proto_goTypes = []any{
	(*Message)(nil),                  // 0: streamflow.v1.Message
	(*ProduceRequest)(nil),           // 1: streamflow.v1.ProduceRequest
	(*ProduceResponse)(nil),          // 2: streamflow.v1.ProduceResponse
	(*ProduceResult)(nil),            // 3: streamflow.v1.ProduceResult
	(*ConsumeRequest)(nil),           // 4: streamflow.v1.ConsumeRequest
	(*ConsumeResponse)(nil),          // 5: streamflow.v1.ConsumeResponse
	(*HealthRequest)(nil),            // 6: streamflow.v1.HealthRequest
	(*HealthResponse)(nil),           // 7: streamflow.v1.HealthResponse
	(*ListPartitionsRequest)(nil),    // 8: streamflow.v1.ListPartitionsRequest
	(*ListPartitionsResponse)(nil),   // 9: streamflow.v1.ListPartitionsResponse
	(*PartitionInfo)(nil),            // 10: streamflow.v1.PartitionInfo
	(*RebalanceRequest)(nil),         // 11: streamflow.v1.RebalanceRequest
	(*RebalanceResponse)(nil),        // 12: streamflow.v1.RebalanceResponse
	(*PartitionMetricsRequest)(nil),  // 13: streamflow.v1.PartitionMetricsRequest
	(*PartitionMetricsResponse)(nil), // 14: streamflow.v1.PartitionMetricsResponse
	(*PartitionMetrics)(nil),         // 15: streamflow.v1.PartitionMetrics
	(*ScalePartitionsRequest)(nil),   // 16: streamflow.v1.ScalePartitionsRequest
	(*ScalePartitionsResponse)(nil),  // 17: streamflow.v1.ScalePartitionsResponse
	(*JoinGroupRequest)(nil),         // 18: streamflow.v1.JoinGroupRequest
	(*JoinGroupResponse)(nil),        // 19: streamflow.v1.JoinGroupResponse
	(*LeaveGroupRequest)(nil),        // 20: streamflow.v1.LeaveGroupRequest
	(*LeaveGroupResponse)(nil),       // 21: streamflow.v1.LeaveGroupResponse
	(*HeartbeatRequest)(nil),         // 22: streamflow.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 23: streamflow.v1.HeartbeatResponse
	(*GroupInfoRequest)(nil),         // 24: streamflow.v1.GroupInfoRequest
	(*GroupInfoResponse)(nil),        // 25: streamflow.v1.GroupInfoResponse
	(*ConsumerMember)(nil),           // 26: streamflow.v1.ConsumerMember
	(*CommitOffsetRequest)(nil),      // 27: streamflow.v1.CommitOffsetRequest
	(*CommitOffsetResponse)(nil),     // 28: streamflow.v1.CommitOffsetResponse
	(*GetOffsetRequest)(nil),         // 29: streamflow.v1.GetOffsetRequest
	(*GetOffsetResponse)(nil),        // 30: streamflow.v1.GetOffsetResponse
	nil,                              // 31: streamflow.v1.HealthResponse.MetricsEntry
	nil,                              // 32: streamflow.v1.RebalanceResponse.PartitionAssignmentsEntry
	nil,                              // 33: streamflow.v1.JoinGroupRequest.MetadataEntry
	nil,                              // 34: streamflow.v1.ConsumerMember.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 35: google.protobuf.Timestamp
}
var file_api_proto_streamflow_proto_depIdxs = []int32{
	35, // 0: streamflow.v1.Message.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: streamflow.v1.ProduceRequest.messages:type_name -> streamflow.v1.Message
	3,  // 2: streamflow.v1.ProduceResponse.results:type_name -> streamflow.v1.ProduceResult
	0,  // 3: streamflow.v1.ConsumeResponse.messages:type_name -> streamflow.v1.Message
	31, // 4: streamflow.v1.HealthResponse.metrics:type_name -> streamflow.v1.HealthResponse.MetricsEntry
	10, // 5: streamflow.v1.ListPartitionsResponse.partitions:type_name -> streamflow.v1.PartitionInfo
	35, // 6: streamflow.v1.PartitionInfo.last_activity:type_name -> google.protobuf.Timestamp
	32, // 7: streamflow.v1.RebalanceResponse.partition_assignments:type_name -> streamflow.v1.RebalanceResponse.PartitionAssignmentsEntry
	15, // 8: streamflow.v1.PartitionMetricsResponse.metrics:type_name -> streamflow.v1.PartitionMetrics
	35, // 9: streamflow.v1.PartitionMetrics.last_activity:type_name -> google.protobuf.Timestamp
	33, // 10: streamflow.v1.JoinGroupRequest.metadata:type_name -> streamflow.v1.JoinGroupRequest.MetadataEntry
	26, // 11: streamflow.v1.GroupInfoResponse.members:type_name -> streamflow.v1.ConsumerMember
	35, // 12: streamflow.v1.GroupInfoResponse.created_at:type_name -> google.protobuf.Timestamp
	35, // 13: streamflow.v1.GroupInfoResponse.last_rebalance:type_name -> google.protobuf.Timestamp
	35, // 14: streamflow.v1.ConsumerMember.last_heartbeat:type_name -> google.protobuf.Timestamp
	34, // 15: streamflow.v1.ConsumerMember.metadata:type_name -> streamflow.v1.ConsumerMember.MetadataEntry
	1,  // 16: streamflow.v1.MessageService.Produce:input_type -> streamflow.v1.ProduceRequest
	4,  // 17: streamflow.v1.MessageService.Consume:input_type -> streamflow.v1.ConsumeRequest
	4,  // 18: streamflow.v1.MessageService.ConsumeBatch:input_type -> streamflow.v1.ConsumeRequest
	27, // 19: streamflow.v1.MessageService.CommitOffset:input_type -> streamflow.v1.CommitOffsetRequest
	29, // 20: streamflow.v1.MessageService.GetOffset:input_type -> streamflow.v1.GetOffsetRequest
	6,  // 21: streamflow.v1.MessageService.Health:input_type -> streamflow.v1.HealthRequest
	8,  // 22: streamflow.v1.PartitionService.ListPartitions:input_type -> streamflow.v1.ListPartitionsRequest
	11, // 23: streamflow.v1.PartitionService.RebalancePartitions:input_type -> streamflow.v1.RebalanceRequest
	13, // 24: streamflow.v1.PartitionService.GetPartitionMetrics:input_type -> streamflow.v1.PartitionMetricsRequest
	16, // 25: streamflow.v1.PartitionService.ScalePartitions:input_type -> streamflow.v1.ScalePartitionsRequest
	18, // 26: streamflow.v1.ConsumerGroupService.JoinGroup:input_type -> streamflow.v1.JoinGroupRequest
	20, // 27: streamflow.v1.ConsumerGroupService.LeaveGroup:input_type -> streamflow.v1.LeaveGroupRequest
	22, // 28: streamflow.v1.ConsumerGroupService.Heartbeat:input_type -> streamflow.v1.HeartbeatRequest
	24, // 29: streamflow.v1.ConsumerGroupService.GetGroupInfo:input_type -> streamflow.v1.GroupInfoRequest
	2,  // 30: streamflow.v1.MessageService.Produce:output_type -> streamflow.v1.ProduceResponse
	5,  // 31: streamflow.v1.MessageService.Consume:output_type -> streamflow.v1.ConsumeResponse
	5,  // 32: streamflow.v1.MessageService.ConsumeBatch:output_type -> streamflow.v1.ConsumeResponse
	28, // 33: streamflow.v1.MessageService.CommitOffset:output_type -> streamflow.v1.CommitOffsetResponse
	30, // 34: streamflow.v1.MessageService.GetOffset:output_type -> streamflow.v1.GetOffsetResponse
	7,  // 35: streamflow.v1.MessageService.Health:output_type -> streamflow.v1.HealthResponse
	9,  // 36: streamflow.v1.PartitionService.ListPartitions:output_type -> streamflow.v1.ListPartitionsResponse
	12, // 37: streamflow.v1.PartitionService.RebalancePartitions:output_type -> streamflow.v1.RebalanceResponse
	14, // 38: streamflow.v1.PartitionService.GetPartitionMetrics:output_type -> streamflow.v1.PartitionMetricsResponse
	17, // 39: streamflow.v1.PartitionService.ScalePartitions:output_type -> streamflow.v1.ScalePartitionsResponse
	19, // 40: streamflow.v1.ConsumerGroupService.JoinGroup:output_type -> streamflow.v1.JoinGroupResponse
	21, // 41: streamflow.v1.ConsumerGroupService.LeaveGroup:output_type -> streamflow.v1.LeaveGroupResponse
	23, // 42: streamflow.v1.ConsumerGroupService.Heartbeat:output_type -> streamflow.v1.HeartbeatResponse
	25, // 43: streamflow.v1.ConsumerGroupService.GetGroupInfo:output_type -> streamflow.v1.GroupInfoResponse
	30, // [30:44] is the sub-list for method output_type
	16, // [16:30] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_streamflow_proto_init() }
func file_api_proto_streamflow_proto_init() {
	if File_api_proto_streamflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_streamflow_proto_rawDesc), len(file_api_proto_streamflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_proto_streamflow_proto_goTypes,
		DependencyIndexes: file_api_proto_streamflow_proto_depIdxs,
		MessageInfos:      file_api_proto_streamflow_proto_msgTypes,
	}.Build()
	File_api_proto_streamflow_proto = out.File
	file_api_proto_streamflow_proto_goTypes = nil
	file_api_proto_streamflow_proto_depIdxs = nil
}
